### ISSUE TITLE
Add a calendar / clock with bomb start time

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-factory#30]
Please consider adding a clock / calendar thing (pick-up able?) that has the bomb start time and date.

I think that might be impossible to add to the normal gameplay room and this is the room with the most active development.  If it was there, then I'd be willing to do Dating Sim.

If you can add it to the normal gameplay room, that would be even more awesome.

**Comment by ashbash1987** [comment]
Here are some preview images of what it currently looks like:

![f4f8ae7acb45a5ac1a29f726be4a58e0](https://user-images.githubusercontent.com/807467/35304211-9d188d5a-008c-11e8-820d-759a51545ff6.png)

![f813702563f75898da62c2fa0da2d6b3](https://user-images.githubusercontent.com/807467/35304216-a146bb9a-008c-11e8-8e02-6918d6f532f9.jpg)

**Comment by ashbash1987** [comment]
I'm gonna consider this done for the time being, unless there's public outcry for a 'bomb start' time display somewhere.
